version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: citis_postgres
    environment:
      POSTGRES_DB: citis_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: